steps:
  # 1. Build the API Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/multidimensions/sales-assistant-api:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/multidimensions/sales-assistant-api:latest'
      - '-f'
      - '05_api/Dockerfile'
      - '.'

  # 2. Push the API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/multidimensions/sales-assistant-api:$COMMIT_SHA'

  # 3. Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'multidimensions-api'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/multidimensions/sales-assistant-api:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8000'
      - '--cpu'
      - '8'
      - '--memory'
      - '32Gi'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
      - '--gpu'
      - '1'
      - '--gpu-type'
      - 'nvidia-l4'
      - '--no-gpu-zonal-redundancy'
      - '--quiet'

  # 4. Build the Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/multidimensions/sales-assistant-frontend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/multidimensions/sales-assistant-frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://multidimensions-api-571181295708.asia-southeast1.run.app'
      - '-f'
      - '06_frontend/Dockerfile'
      - './06_frontend'

  # 5. Push the Frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/multidimensions/sales-assistant-frontend:$COMMIT_SHA'

  # 6. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'multidimensions-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/multidimensions/sales-assistant-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY
